[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
disk = { path = "../disk" }
logical = { path = "../logical" }
nunny = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
syscalls = { path = "../syscalls" }
thiserror = { workspace = true }
